FROM docker.io/nginx:mainline-alpine

RUN apk add --update npm

RUN mkdir frontend
WORKDIR frontend
COPY frontend .


RUN npm install
RUN npm run build

RUN rm -rf /usr/share/nginx/html
RUN mv target/classes/static /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
RUN mv default.conf /etc/nginx/conf.d

