FROM docker.io/maven:3-eclipse-temurin-17

RUN mkdir backend
WORKDIR backend
COPY backend .

RUN mvn --settings ./setting.xml package -Pprod 


CMD java -jar target/boardgamemanager-0.0.1-SNAPSHOT.jar

